nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/jacekk

projects_url: http://github.com/jacekk

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        # github: http://github.com/jacekk
        # twitter: /
        # facebook: /
        # linkedin: /
    post_count: 10
    highlight: rainbow

# RSS
rss: atom.xml

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
